britelearn/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using britelearn.Data;
using britelearn.Data.Models;
using britelearn.Data.Interfaces;
using britelearn.Data.Repositories;
using britelearn.ViewModels;


namespace britelearn.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {

        private ICategoryRepository _categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_categoryRepository.GetAllCategories());
        }
        public IActionResult Create() => View();
        public IActionResult Created(Category category)
        {

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Something went wrong!");
                return View("Create");
            }
            _categoryRepository.AddCategory(category);
            return View();
        }


        public IActionResult Edit(int id) => View(_categoryRepository.GetSingleCategoryById(id));


        public IActionResult Edited(Category newCategory)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Something went wrong!");
                return View("EditCategory", newCategory);
            }
            _categoryRepository.UpdateCategory(newCategory);

            return View();

        }

        public IActionResult Delete(int id) => View(_categoryRepository.CategoryDeletionConfirmation(id));


        public IActionResult Deleted(int id)
        {
            _categoryRepository.DeleteCategories(id);
            return View();
        }

    }
}

britelearn/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using britelearn.Data.Interfaces;
using britelearn.Data.Models;
using britelearn.ViewModels;
using britelearn.ViewModels.Topic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace britelearn.Controllers
{
    [Authorize]
    public class TopicController : Controller
    {
        private readonly ITopicRepository _TopicRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IExampleRepository _exampleRepository;
        private readonly ICaveatRepository _caveatRepository;

        public TopicController(ITopicRepository TopicRepository, ICategoryRepository categoryRepository, IExampleRepository exampleRepository, ICaveatRepository caveatRepository)
        {
            _TopicRepository = TopicRepository;
            _categoryRepository = categoryRepository;
            _exampleRepository = exampleRepository;
            _caveatRepository = caveatRepository;
        }

        [AllowAnonymous]
        public ViewResult List(string category)
        {
      
            
            string _category = category;
            IEnumerable<Topic> topics;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                topics = _TopicRepository.GetAllTopic().OrderBy(p => p.TopicId);
                currentCategory = "All";
            }
            else
            {
                //if (string.Equals(category, _category, StringComparison.OrdinalIgnoreCase))
                //{
                    topics = _TopicRepository.GetAllTopic().Where(p => p.Category.CategoryName.Equals(_category)).OrderBy(p => p.Name);
                //}
                //else
                //    topics = _TopicRepository.Topics.Where(p => p.Category.CategoryName.Equals(category)).OrderBy(p => p.Name);

                currentCategory = _category;
            }
             
            return View(new TopicsListViewModel
            {
                Topics = topics,
                CurrentCategory = currentCategory
            });
        }

        [AllowAnonymous]
        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Topic> Topics;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                Topics = _TopicRepository.GetAllTopic().OrderBy(p => p.TopicId);
            }
            else
            {
                Topics = _TopicRepository.GetAllTopic().Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Topic/List.cshtml", new TopicsListViewModel { Topics = Topics, CurrentCategory = "All Topics" });
        }

        [AllowAnonymous]
        public ViewResult Details(int topicId)
        {
            var topic = _TopicRepository.GetAllTopic().FirstOrDefault(d => d.TopicId == topicId);

            IEnumerable<Example> examples = null;
            IEnumerable<Caveat> caveats = null;

            if (topic != null)
            {
                examples = _exampleRepository.GetExampleByTopicId(topicId).OrderBy(e => e.ExampleOrder);
                caveats = _caveatRepository.GetCaveatByTopicId(topicId);

                TopicViewModel vm = new TopicViewModel
                {
                    TopicId = topic.TopicId,
                    Name = topic.Name,
                    Description = topic.Description,
                    ImageThumbnailUrl = topic.ImageThumbnailUrl,
                    Caveats = caveats,
                    Examples = examples

                };

                return View(vm);
            }

            else
                return View("~/Views/Error/Error.cshtml");


        }


        /** Admin details **/

        [AllowAnonymous]
        public IActionResult Index ()
        {
            return View(_TopicRepository.GetAllTopic());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = _categoryRepository.GetAllCategories();
            return View();
        }

        [HttpPost]
        public IActionResult Created(TopicCreateViewModel topicView)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Something went wrong");
            
                return View("Create");
            }

            _TopicRepository.AddTopic(topicView);

            return View();
        }
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = _categoryRepository.GetAllCategories();
            return View(_TopicRepository.GetSingleTopicById(id));
        }
        public IActionResult Edited(Topic newTopic)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Something went wrong");
                ViewBag.Categories = _categoryRepository.GetAllCategories();
                return View("Edit", newTopic);
            }
            _TopicRepository.UpdateTopic(newTopic);
            return View();

        }

        public IActionResult Delete(int id) => View(_TopicRepository.GetSingleTopicById(id));

        public IActionResult Deleted(int id)
        {
            _TopicRepository.DeleteTopic(id);

            return View();
        }
        public IActionResult TopicDetails(int id)
        {
            return View(_TopicRepository.TopicDetails(id));
        }
    }
}

britelearn/Views/Shared/CaveatView.cshtml
@model Caveat

<h4>@Model.CaveatName</h4>
<p>@Model.CaveatDiscription</p>

britelearn/Views/Shared/ExampleEdit.cshtml
@model Example

britelearn/Views/Shared/ExampleView.cshtml
@model Example

<div class="title">
    <h2>@Model.ExampleHeading</h2>
</div>

<div class="tile">

    <div class="row">

        @Model.ExampleText

    </div>
</div>

britelearn/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul @*class="nav navbar-nav navbar-right"*@>
            <li class="profile-list"><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul @*class="nav navbar-nav navbar-right"*@>
        <li class="profile-list"><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li class="profile-list"><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

britelearn/Views/Shared/TopicOverviewSummary.cshtml
@model Topic

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        
        <img src="@Model.ImageThumbnailUrl" alt="" />
        
        <div class="caption">
            <h3>
                <a asp-controller="Topic" asp-action="Details" asp-route-id="@Model.TopicId">@Model.Name</a>
            </h3>
            <p>@Model.Description</p>
        </div>

    </div>
</div>

britelearn/Views/Shared/TopicsSummary.cshtml
@model Topic

@*<div class="align-items-center justify-content-center d-flex ">*@
<div class="card col-lg-5 col-md-5 col-sm-4">
  


    <div class=" text-center card-header">
        
        <h2 > @Model.Name</h2>
    </div>

    <div class="card-body row">
        @*<div class="advance-div d-flex col-md-4 ">
        @*advance-div   col-md-4 *@

        @*<img src="https://weneedfun.com/wp-content/uploads/2016/07/Girls-Black-and-White-Profile-Pictures-8.jpg"
        class="rounded-circle img-profile " alt="Avatar">*@

        @*<a asp-controller="Topic" asp-action="Details" asp-route-topicId="@Model.TopicId">
                        <svg class="advance-icon" xmlns="http://www.w3.org/2000/svg" viewBox="-3 0 25 25" width="100" height="100">
                            <path d="M6.028 0v6.425l5.549 5.575-5.549 5.575v6.425l11.944-12z" />
                        </svg>
                    </a>

        <img src="@Model.ImageThumbnailUrl" alt="" />
                </div>*@op[]0
       
        <div class="col-lg-4 col-md-12 advance-div" style="">
            <img src="@Model.ImageThumbnailUrl"
                 class="" alt="" style="">

            <a style="" asp-controller="Topic" asp-action="Details" asp-route-topicId="@Model.TopicId">
                <svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="-3 0 25 25" width="100" height="100">
                    <path d="M6.028 0v6.425l5.549 5.575-5.549 5.575v6.425l11.944-12z" />
                </svg>
            </a>
        </div>



        <div class=" col-lg-8 col-md-12 text">
            <p>
                @Model.Description
            </p>
        </div>

        <div id="@Model.TopicId" class=" collapse row dropdown" style="margin-left: 0; margin-right: 0;">
            <div class="col-md-4 col-sm-12 tag-div">

                @*!!Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.!!*@
                <span class="badge badge-pill badge-info">C#</span>
                <span class="badge badge-pill badge-info">Primary Label</span>
                <span class="badge badge-pill badge-info">Primary Label</span>
                <span class="badge badge-pill badge-info">Primary Label</span>
                <span class="badge badge-pill badge-info">Primary Label</span>
            </div>

            <div class="col-md-8 col-sm-12 info-div">
                @*<a><p>
                    @Model.Name
                    donec ultrices tincidunt arcu non. Lectus mauris ultrices eros in. Faucibus a
                    pellentesque sit amet porttitor eget dolor morbi non. Eu non diam phasellus vestibulum lorem sed. Integer e
                    get aliquet nibh praesent tristique
                </p></a>*@

                @*Velit laoreet id donec ultrices tincidunt arcu non. Lectus mauris ultrices eros in. Faucibus a
                pellentesque sit amet porttitor eget dolor morbi non. Eu non diam phasellus vestibulum lorem sed. Integer e
                get aliquet nibh praesent tristique magna sit amet purus. Pretium fusce id velit ut tortor pretium.
                Consectetur adipiscing elit ut aliquam purus sit amet luctus.*@
                <a class="nav-link" asp-controller="Topic" asp-action="List"
                   asp-route-category="@Model.Category.CategoryName"><p>@Model.Category.CategoryName</p></a>
            </div>
        </div>

    </div>

    <div id="footer_@Model.TopicId" class="  card-footer" data-toggle="collapse" data-target="#@Model.TopicId">

        @*<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">Simple collapsible</button>*@
        <svg id="svg_@Model.TopicId" @*type="button" *@ class="md-icon" width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd">
            <path d="M23.247 4l-11.247 14.44-11.263-13.44-.737.678 12 14.322 12-15.335-.753-.665z" />
        </svg>

    </div>
</div>
@*</div>*@


<script>
    var toggle;
    toggle = 1;

    $('#footer_@Model.TopicId').click(function () {
        @*$('#svg_@Model.TopicId').css('transform', 'rotate(180deg)');*@
         @*$('#svg_@Model.TopicId').toggle('rotated');*@
        if (toggle == 1) {
          
            $('#svg_@Model.TopicId').css('transform', 'scale(1,-1) ');
            toggle = 0;
        }
        else {
            $('#svg_@Model.TopicId').css('transform', 'scale(-1,1) ');
            toggle = 1;

        }
    });

    //document.querySelector('md-icon').addEventListener('click', function () {
    //    this.classList.toggle('rotated');
    //});
</script>

britelearn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewData["Title"] - britelearn</title>
    @using Microsoft.AspNetCore.Identity
    @model List<Topic>
    @inject SignInManager<IdentityUser> SignInManager*@

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/Site.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script>
        //$(document).ready(function () {
        //    $("button").click(function () {

        //        //
        //        alert("Handler for .click() called.");
        //});

        function toggleSide() {

            //$("#test").toggleClass("side-inactive");
            $("#test").toggle();
            $("#main").toggleClass("col-md-9");
            $("#main").toggleClass("col-md-12");

            $("#main").toggleClass("col-lg-10");
            $("#main").toggleClass("col-lg-12");

            //alert("Handler for .click() called.");
        }


    </script>



</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
        <a class="navbar-brand text-center logo" asp-area="" asp-controller="Home" asp-action="Index">Brite Learn</a>
        <button onclick="toggleSide()" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-chevron-left"></i></button>  @*data-toggle="collapse" data-target="#test"*@


        <!-- Navbar links
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Topic" asp-action="List">Topics</a></li>
            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Profile">Profile</a></li>
        </ul>


    </div> -->


        <form class="form-inline nav-search" asp-controller="Topic" asp-action="Search" method="get">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">S</span>
                </div>
                <input type="text" class="form-control" placeholder="Search" name="searchString" value="@ViewData["searchString"]">
            </div>
        </form>

        <!-- Toggler/collapsibe Button
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button> -->

        <!--ADMIN-->
        <div class="profile-icon pull-right ml-auto">
            <ul class="nav">

                <li class="dropdown">

                    <svg class="dropdown-toggle" data-toggle="dropdown" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M24 13.616v-3.232c-1.651-.587-2.694-.752-3.219-2.019v-.001c-.527-1.271.1-2.134.847-3.707l-2.285-2.285c-1.561.742-2.433 1.375-3.707.847h-.001c-1.269-.526-1.435-1.576-2.019-3.219h-3.232c-.582 1.635-.749 2.692-2.019
                          3.219h-.001c-1.271.528-2.132-.098-3.707-.847l-2.285 2.285c.745 1.568 1.375 2.434.847 3.707-.527 1.271-1.584 1.438-3.219 
                          2.02v3.232c1.632.58 2.692.749 3.219 2.019.53 1.282-.114 2.166-.847 3.707l2.285 2.286c1.562-.743 2.434-1.375 3.707-.847h.001c1.27.526 1.436 1.579 2.019 3.219h3.232c.582-1.636.75-2.69 
                          2.027-3.222h.001c1.262-.524 2.12.101 3.698.851l2.285-2.286c-.744-1.563-1.375-2.433-.848-3.706.527-1.271 1.588-1.44 3.221-2.021zm-12 2.384c-2.209 0-4-1.791-4-4s1.791-4 4-4 4 1.791 4 4-1.791 4-4 4z" /></svg>

                    <div class="dropdown-menu dropdown-menu-right">
                        <ul>

                            <li class="profile-list"><a asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                            <li class="profile-list"><a asp-area="" asp-controller="Topic" asp-action="Index">Topic</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>


        <div class="profile-icon pull-right ml-auto">
            <ul class="nav">

                <li class="dropdown">


                    <svg class="dropdown-toggle" data-toggle="dropdown" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm0
                                22c-3.123 0-5.914-1.441-7.749-3.69.259-.588.783-.995 1.867-1.246 2.244-.518 4.459-.981
                                3.393-2.945-3.155-5.82-.899-9.119 2.489-9.119 3.322 0 5.634 3.177 2.489 9.119-1.035
                                1.952 1.1 2.416 3.393 2.945 1.082.25 1.61.655 1.871 1.241-1.836 2.253-4.628 3.695-7.753 3.695z" />
                    </svg>

                    <div class="dropdown-menu dropdown-menu-right">
                        <ul>
                            @*<li class="profile-list"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="profile-list"><a asp-area="" asp-controller="Topic" asp-action="List">Topics</a></li>*@
                            <li class="profile-list"><a asp-area="" asp-controller="Account" asp-action="Profile">Profile</a></li>
                            @*<li class="profile-list"><a asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>*@
                        </ul>
                        @await Html.PartialAsync("LoginPartial")
                    </div>
                </li>
            </ul>
        </div>



    </nav>

    <div class="container-fluid text-center">
        <div class=" content row row-offcanvas row-offcanvas-left">
            <div id="test" class=" white-space  col-lg-2   col-md-3">
                <div class="sidenav flex-column  col-lg-2   col-md-3">
                    @*col-lg-3   col-md-4*@

                    <form class="" asp-controller="Topic" asp-action="Search" method="get" style="padding: 0;">
                        <div class="form-group input-group d-flex justify-content-center">
                            <div class="input-group-prepend">
                                <span class="input-group-text">S</span>
                            </div>
                            <input type="text" class="form-control" placeholder="Search for a Topic" name="searchString" value="@ViewData["searchString"]">
                        </div>
                    </form>
                    @await Component.InvokeAsync("CategoryMenu")

                </div>
            </div>
     
            <div id="main" class="col-lg-10 col-md-9 page-content">
                @*col-lg-9 col-md-8*@
                @RenderBody()

            </div>





            <footer class="col-12" style="margin-top: 20px">
                <p>&copy; @DateTime.Now.Year - Legitimate Indestries</p>
            </footer>


        </div>





    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>